import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Toaster} from "react-hot-toast";
import Navigation from "@/src/components/nav/Navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster
            position={"top-center"}
        ></Toaster>
        <div className={"w-full"}>
          <Navigation></Navigation>

        </div>

        <main className={"flex-1 container mx-auto px-4 py-8 max-w-md md:max-w-2xl lg:max-w-4xl"}>
            {children}
        </main>
      </body>
    </html>
  );
}
